### ISSUE TITLE
Please consider renaming this project

### ISSUE THREAD

**Issue by Randgalt** [hkupty/penna#24]
I've had a structured logging library for more than 2 years named Maple. https://github.com/Randgalt/maple

**Comment by hkupty** [comment]
I'm sorry for the inconvenience. Do you believe that you will reactivate your project in the near future? I want to take some time to consider the name and the possible options so I don't clash with any other project. Naming is hard and if this is too much of a problem for you I'll have to decide on something sooner, so at least I want to understand what are my options to move forward.

Furthermore, given the terseness of your message, I can't really understand your feelings regarding this unfortunate coincidence, so it is difficult for me to assess the urgency and importance of solving this matter.

Thanks in advance

**Comment by Randgalt** [comment]
My project is not inactive. I’m not angry or anything but, if the situation was reversed, I’d immediately rename. Your project is new and it doesn’t seem like a burden on you.

**Comment by hkupty** [comment]
It is not a burden and I am not opposing to rename.
I understood your project was inactive because its last commit was over two years ago.

All I want is to understand whether this is a pressing issue - that you expect me to rename immediately - or if I have time to look for an alternative so I don't clash with other existing software and I can pick a name that I understand it to be both meaningful and to sound nice.

I don't want to rename the project to oak, then find out another project has the same name, then end up renaming this to birch.

**Comment by Randgalt** [comment]
Not pressing at all and totally up to you. Thank you.

**Comment by hkupty** [comment]
Thank you as well. I'll close this issue once I find the appropriate name to replace.

**Comment by Randgalt** [comment]
Thank you - this was very nice of you.
